// <auto-generated />
using AutoMapperBlog.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoMapperBlog.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("AutoMapperBlog.Data.Entities.DepartmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("AutoMapperBlog.Data.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "John",
                            LastName = "Smith",
                            Salary = 35000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            FirstName = "Mary",
                            LastName = "Jones",
                            Salary = 42000m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            FirstName = "Mel",
                            LastName = "Black",
                            Salary = 25000m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            FirstName = "Jack",
                            LastName = "White",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            FirstName = "Jess",
                            LastName = "Tan",
                            Salary = 47000m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            FirstName = "Steve",
                            LastName = "Davies",
                            Salary = 22000m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            FirstName = "Emma",
                            LastName = "Williams",
                            Salary = 47500m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            FirstName = "Darren",
                            LastName = "Miller",
                            Salary = 28000m
                        });
                });

            modelBuilder.Entity("AutoMapperBlog.Data.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("AutoMapperBlog.Data.Entities.DepartmentEntity", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AutoMapperBlog.Data.Entities.DepartmentEntity", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
